DjangoWeb/urls.py
from django.contrib import admin
from django.urls import path
from testapp import views
from django.conf.urls import include,url
import xadmin
from testapp import urls
xadmin.autodiscover()
from xadmin.plugins import xversion
xversion.register_models()
urlpatterns = [
    #url('admin/', admin.site.urls),
    path(r'xadmin/', xadmin.site.urls),
    path('',include('testapp.urls')),
]

testapp/urls.py
from django.conf.urls import url, include
from testapp import views

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
handlerw404 = "testapp.views.page_not_found"
handlerw500 = "testapp.views.page_error"
urlpatterns = [
    url(r'^index/', views.index),
    url(r'^cp_index/', views.cp_index),
    url(r'^login/', views.login),
    url(r'^test/', views.test),
    url(r'^cplogin/', views.cp_login),
    url(r'^register/', views.register),
    url(r'^change_o/(\w+)/$', views.Change_o),
    url(r'^c_change/$', views.C_change),
    url(r'^is_apply/(\w+)/',views.is_offer),
    url(r'^classes/(\w+)/', views.Classes),
    url(r'^mylove/(\w+)/', views.Mylove),
    url(r'^show_o/(\w+)/', views.show_o),
    url(r'^allinfo/(\w+)/', views.all_info),
    url(r'^mana/(\w+)/$', views.Info_mana),
    url(r'^add_say/$', views.add_say,name='add_say'),
    url(r'^add_info/(\w+)/$', views.addinfo),
    url(r'^cpregister/', views.cp_register),
    url(r'^logout/', views.logout),
    url(r'^del/(\d+)/', views.del_info),
    url(r'^fav/(\d+)/(\w+)/', views.Favorite),
    url(r'^apply/(\d+)/(\w+)/', views.apply),
    url(r'^details/(\d+)/(\w+)/', views.Showdetails, name='showd'),
    url(r'^search/(\d+)/$', views.Search),


]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

testapp/models.py
from django.db import models
import django.utils.timezone as timezone
# Create your models here.
gender=(
    ('male','男'),
    ('female','女')
)
class_choice=(
    ('it','计算机'),
    ('service','服务业'),
    ('financial','金融'),
    ('realty','房地产'),
    ('medical','医疗'),
    ('education','教育'),
)
class User(models.Model):
    userid=models.AutoField(primary_key=True)
    user_name=models.CharField('账号',max_length=128)
    user_title=models.CharField('昵称',max_length=30)
    password=models.CharField('密码',max_length=256)
    createdate=models.DateTimeField('创建时间',auto_now_add=True,editable=True, null=True)
    user_email=models.EmailField('邮箱')
    user_sex=models.CharField('性别',max_length=20,choices=gender)
    user_tel=models.CharField('电话',max_length=20)
    address=models.CharField('地址',max_length=80)
    user_about=models.CharField('自我介绍',max_length=100)
    user_img=models.ImageField('头像',max_length=256,upload_to='img',default="img/default.png")
    #user_file=models.FileField('简历文件')
    class Meta:
        verbose_name = '用户'
        db_table='User'

class Company(models.Model):
    cp_id = models.AutoField(primary_key=True)
    cp_name = models.CharField('账号', max_length=128)
    cp_title = models.CharField('公司名', max_length=30)
    password = models.CharField('密码', max_length=256)
    createdate = models.DateTimeField('创建时间', auto_now_add=True,editable=True, null=True)
    cp_email = models.EmailField('邮箱')
    cp_tel = models.CharField('电话', max_length=20)
    cp_address = models.CharField('地址', max_length=80)
    cp_about = models.CharField('自我介绍', max_length=100)
    cp_img=models.ImageField('头像',max_length=256,upload_to='img',default="img/default.png")
    # user_file=models.FileField('介绍文件')
    class Meta:
        verbose_name = '公司'
        db_table='Company'
index_hot={
    ('yes', 'yes'),
    ('no', 'no'),
}

class Information(models.Model):
    info_id=models.AutoField(primary_key=True)
    cp_title=models.CharField('公司名', max_length=30)
    createdate=models.DateTimeField('发布时间',auto_now_add=True,editable=True, null=True)
    job=models.CharField('职位',max_length=20,default='')
    classes=models.CharField('类别',max_length=20,choices=class_choice)
    cp_email = models.EmailField('邮箱')
    pay=models.CharField('薪酬',max_length=50,default='3000-5000')
    cp_tel = models.CharField('电话', max_length=20)
    cp_address = models.CharField('地址', max_length=80)
    info=models.TextField('招聘内容')
    info_img=models.ImageField('图片',max_length=256,upload_to='img')
    views = models.PositiveIntegerField(default=0)
    is_hot=models.CharField('首页轮播',max_length=10,choices=index_hot,default='no')
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])
    class Meta:
        verbose_name = '招聘信息'
        db_table='Info'

class Comments(models.Model):
    com_id=models.AutoField(primary_key=True)
    info_id = models.CharField(max_length=256,default='')
    user_name = models.CharField(max_length=128, default='')
    user_title = models.CharField('昵称', max_length=30, default='')
    pay = models.CharField('薪酬', max_length=50, default='3000-5000')
    com_about=models.CharField('内容', max_length=30)
    com_time=models.DateTimeField('发布时间',auto_now_add=True,editable=True, null=True)

    class Meta:
        verbose_name = '评论'
        db_table='Com'
class Collection(models.Model):
    id=models.AutoField(primary_key=True)
    user_name=models.CharField(max_length=128)
    info_id=models.CharField(max_length=256)
    pay = models.CharField('薪酬', max_length=50, default='3000-5000')
    cp_title = models.CharField('公司名', max_length=30, default='')
    job = models.CharField('职位', max_length=20, default='')
    col_time = models.DateTimeField('收藏时间', auto_now_add=True, editable=True, null=True)
    class Meta:
        verbose_name = '用户收藏'
        db_table='Col'

class C_collection(models.Model):
    id = models.AutoField(primary_key=True)
    user_title=models.CharField(max_length=30, default='')
    user_name = models.CharField(max_length=128, default='')
    cp_title=models.CharField(max_length=30, default='')
    job = models.CharField('职位', max_length=20, default='')
    info_id = models.CharField(max_length=256,default='')
    pay = models.CharField('薪酬', max_length=50, default='3000-5000')
    c_time = models.DateTimeField('投递时间', auto_now_add=True,editable=True, null=True)
    is_look=models.CharField('已查看',max_length=10,choices=index_hot,default='no')
    class Meta:
        verbose_name = '简历'
        db_table = 'C_col'
class Relationship(models.Model):
    id=models.AutoField(primary_key=True)
    user=models.ManyToManyField(User)
    com=models.ManyToManyField(Comments)
    company=models.ManyToManyField(Company)
    info=models.ManyToManyField(Information)
    col=models.ManyToManyField(Collection)
    class Meta:
        verbose_name = '关联'
        db_table='Relationship'

templates/add_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>发布招聘</title>
     <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="/static/js/jquery-3.4.1.js"></script>
	<script src="/static/bootstrap-4.3.1-dist/js/bootstrap.min.js"></script>
<style>
    .input1{
        height: 300px;
        width: 500px;
    }
</style>

        <script>
            {% if succ %}
        alert('{{ succ }}')
            {% endif %}
        </script>

</head>
<body>
{% if succ %}
    <a href="/cp_index">返回主页</a>
{% endif %}
 <div class="container">
        <div class="col-md-4 col-md-offset-4">

          <form class='form-register' action="/add_info/{{ request.session.cp_name }}/" method="post" enctype="multipart/form-data">

              {% if succ %}
                  <div class="alert alert-warning">{{ succ }}</div>
              {% endif %}

              {% csrf_token %}
   {% for info in add_info %}
              <h2 class="text-center">发布招聘</h2>
                公司名称：<input type="text" name="cp_title" value="{{ info.cp_title }}"><br>
                岗位：<input type="text" name="job" ><br>
                薪酬：<input type="text" name="pay" ><br>
                岗位类别：<select name="classes">
                    <option value="it">计算机</option>
                    <option value="service">服务业</option>
                    <option value="financial">金融</option>
                    <option value="realty">房地产</option>
                    <option value="medical">医疗</option>
                    <option value="education">教育</option>

                    </select><br>
                公司邮箱：<input type="email" name="cp_email" value="{{ info.cp_email }}"><br>
                公司电话：<input type="text" name="cp_tel" value="{{ info.cp_tel }}"><br>
                公司地址<input type="text" name="cp_address" value="{{ info.cp_address }}"><br>
                岗位描述：<textarea cols="40" rows="7" name="info" ></textarea><br>
                宣传图：<input type="file" name="info_img" >
              <button type="reset" class="btn btn-default pull-left">重置</button>
              <button type="submit" class="btn btn-primary pull-right">提交</button>
 {% endfor %}
   <!--<button type="reset" class="btn btn-default pull-left">重置</button>
              <button type="submit" class="btn btn-primary pull-right">提交</button>-->
          </form>

        </div>
    </div> <!-- /container -->

</body>

templates/bar-tick-align.html
<!DOCTYPE html>
<html style="height: 100%">
   <head>
       <meta charset="utf-8">
   </head>
   <body style="height: 100%; margin: 0">
       <div id="container" style="height: 100%"></div>
       <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts/dist/echarts.min.js"></script>
       <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts-gl/dist/echarts-gl.min.js"></script>
       <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts-stat/dist/ecStat.min.js"></script>
       <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts/dist/extension/dataTool.min.js"></script>
       <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts/map/js/china.js"></script>
       <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts/map/js/world.js"></script>
       <script type="text/javascript" src="https://api.map.baidu.com/api?v=2.0&ak=xfhhaTThl11qYVrqLZii6w8qE5ggnhrY&__ec_v__=20190126"></script>
       <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts/dist/extension/bmap.min.js"></script>
       <script type="text/javascript">
var dom = document.getElementById("container");
var myChart = echarts.init(dom);
var app = {};
option = null;
option = {
    color: ['#3398DB'],
    tooltip: {
        trigger: 'axis',
        axisPointer: {            // 坐标轴指示器，坐标轴触发有效
            type: 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis: [
        {
            type: 'category',
            data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
            axisTick: {
                alignWithLabel: true
            }
        }
    ],
    yAxis: [
        {
            type: 'value'
        }
    ],
    series: [
        {
            name: '直接访问',
            type: 'bar',
            barWidth: '60%',
            data: [10, 52, 200, 334, 390, 330, 220]
        }
    ]
};
;
if (option && typeof option === "object") {
    myChart.setOption(option, true);
}
       </script>
   </body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="zxx">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="meta description">
    <title>{% block title %}首页{% endblock %}</title>

    <!--=== Favicon ===-->
    <link rel="shortcut icon" href="/static/img/logo1.png" type="image/x-icon" />

    <!-- Google fonts include -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,900%7CYesteryear" rel="stylesheet">

    <!-- All Vendor & plugins CSS include -->
    <link href="/static/css/vendor.css" rel="stylesheet">
    <!-- Main Style CSS -->
    <link href="/static/css/style.css" rel="stylesheet">
<script>
    {% if error_msg %}
    alert("{{ error_msg }}")
    {% endif %}
</script>
   <script type="text/javascript">
            function myCheck()
            {
              var q=document.getElementById("q").value;
              if (q==""){
                  alert('不能为空');
                  return false;
              }
            }
        </script>

<link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!--[if lt IE 9]>
<script src="/oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="/oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

</head>

<body>


    <!-- Start Header Area -->
    <header class="header-area">
        <!-- main header start -->
        <div class="main-header d-none d-lg-block">

            <!-- header middle area start -->
            <div class="header-main-area sticky">
                <div class="container">
                    <div class="row align-items-center position-relative">

                        <!-- start logo area -->
                        <div class="col-lg-2">
                            <div class="logo">
                                <a href="/index">
                                    <img src="/static/img/logo1.png" alt="" style="height: 50px">
                                </a>
                            </div>
                        </div>
                        <!-- start logo area -->

                        <!-- main menu area start -->
                        <div class="col-lg-2 position-static text-right" >
                            <div class="main-menu-area" >
                                 <div class="header-configure-area">
                                <ul class="nav justify-content-end">
                                 <li class="user-hover text-right" ><a href="#">
                                               <span style="font-size: 15px">分类</span>
                                            </a>
                                        <ul class="dropdown-list">
                                        <li><a href="/classes/it/?pindex=1">计算机</a></li>
                                            <li><a href="/classes/service/?pindex=1">服务业</a></li>
                                            <li><a href="/classes/financial/?pindex=1">金融</a></li>
                                            <li><a href="/classes/realty/?pindex=1">房地产</a></li>
                                            <li><a href="/classes/medical/?pindex=1">医疗</a></li>
                                            <li><a href="/classes/education/?pindex=1">教育</a></li>
                                        </ul></li>
                                </ul>
                                 </div>

{#                                <div class="main-menu">#}
{#                                    <!-- main menu navbar start -->#}
{#                                  <div class="header-configure-wrapper">#}
{#                                <div class="header-configure-area">#}
{#                                        <ul class="nav justify-content-end" >#}
{##}
{#                                        </ul>#}
{#                                </div>#}
{#                                  </div>#}
{#                                    <!-- main menu navbar end -->#}
{#                                </div>#}
                            </div>
                        </div>
                        <!-- main menu area end -->

                        <!-- mini cart area start -->
                        <div class="col-lg-8 text-left">
                            <div class="header-configure-wrapper">
                                <div class="header-configure-area">
                                    <ul class="nav justify-content-end">



                                        <form class="navbar-form navbar-left" role="search" action="/search/1/" method="get">

							<input type="text" placeholder="公司/职位" name="q" id="q" class="form-control w-75" value="{{ request.session.q }}"/>
						 <button type="submit" class="btn btn-default" onclick="myCheck()">搜索</button>
					</form>


                                    {% if request.session.is_login %}
                                        <li class="user-hover">
                                            <a href="#">
                                                 <i class="lnr lnr-user"></i>
                                            </a>
                                            <ul class="dropdown-list">
                                                {% if request.session.is_login %}
                                                    <li><a href="/change_o/{{ request.session.user_name }}">{{ request.session.user_name }}</a></li>
                                                     <li><a href="/mylove/{{ request.session.user_name }}/?pindex=1">我的收藏</a></li>
                                                    <li><a href="/is_apply/{{ request.session.user_name }}">已投简历</a></li>
                                                    <li><a href="/logout">注销</a></li>


                                                {% endif %}

                                            </ul>
                                        </li>
                                        {% else %}
                                        <li><a href="/login"><span style="font-size: 14px">个人登录</span></a></li>
                                        <li><a href="/cplogin"><span style="font-size: 14px">企业登录</span></a></li>
                                    {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!-- mini cart area end -->

                    </div>
                </div>
            </div>
            <!-- header middle area end -->
        </div>
        <!-- main header start -->


        <!-- mobile header start -->
        <div class="mobile-header d-lg-none d-md-block sticky">
            <!--mobile header top start -->
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-12">
                        <div class="mobile-main-header">
                            <div class="mobile-logo">
                                <a href="/index">
                                    <img src="../static/img/logo1.png" alt="Brand Logo">
                                </a>
                            </div>
                                <div class="mobile-menu-btn">
                                    <div class="off-canvas-btn">
                                        <i class="lnr lnr-menu"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- mobile header top start -->

        <!-- mobile header end -->
    </header>
    <!-- end Header Area -->
{% block content %}{% endblock %}

    <!-- off-canvas menu start -->
    <aside class="off-canvas-wrapper">
        <div class="off-canvas-overlay"></div>
        <div class="off-canvas-inner-content">
            <div class="btn-close-off-canvas">
                <i class="lnr lnr-cross"></i>
            </div>

            <div class="off-canvas-inner">
 <!-- search box start -->
                <div class="search-box-offcanvas">
                    <form  action="/search/1/" method="get" οnsubmit="return myCheck()">
                        <input type="text" placeholder="公司/职位" name="q" id="q">
                        <button class="search-btn" type="submit" onclick="myCheck()"><i class="lnr lnr-magnifier"></i></button>
                    </form>
                </div>
                <!-- search box end -->

                <div class="mobile-settings">
                    <ul class="nav">
                        <li>
                            <div class="dropdown mobile-top-dropdown" style="text-align: left">

                                    {% if request.session.is_login %}
                                    <a style="text-align: left" href="/change_p/{{ request.session.user_name }}"><p>{{ request.session.user_name }}</p></a>
                                         <a style="text-align: left" href="/mylove/{{ request.session.user_name }}"><p>我的收藏</p></a>
                                        <a style="text-align: left" href="/is_apple/{{ request.session.user_name }}"><p>已投简历</p></a>

                                        <a style="text-align: left" href="/logout"><p>注销</p></a>

                                    {% endif %}

                            </div>
                        </li>
                    </ul>
                </div>

            </div>
        </div>
    </aside>
    <!-- off-canvas menu end -->

<!-- All vendor & plugins & active js include here -->
    <!--All Vendor Js -->
    <script src="/static/js/vendor.js"></script>
    <!-- Active Js -->
    <script src="/static/js/active.js"></script>

</body>

</html>

templates/cp_login.html
<!DOCTYPE html>
<html lang="utf-8">
<head>
	<title>企业登录</title>
		<meta charset="utf-8">
		<link href="/static/css/login_style.css" rel='stylesheet' type='text/css' />
		<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body style="background-color: red">
	 <!-----start-main---->
	 <div class="main" >
		<div class="login-form">
			<h1>企业登录</h1>
					<div class="head">
						<img src="/static/img/user.png" alt=""/>
					</div>
				<form action="/cplogin/" method="post">
                     {% if message %}
                  <div class="alert alert-warning">{{ message }}</div>
              {% endif %}
              {% csrf_token %}
						<input type="text" class="text" placeholder="账号"  name="cp_name">
                    <input type="password" placeholder="密码" name="password">
						{{ login_form.captcha }}
                    <div class="submit">
							<input type="submit" >
					</div>
                <p style="text-align: justify"><a href="/login">个人登录</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;<a href="/cpregister/" style="margin-left: 100px">注册</a></p>
				</form>
			</div>
			<!--//End-login-form-->
		</div>
			 <!-----//end-main---->


</body>
</html>

templates/cp_mana.html
{% extends 'cp_index.html' %}
{% block title %}管理{% endblock %}
<script src="/static/js/mana.js"></script>
<script type="text/javascript" src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
    var arr=$(".div li:not(:hidden)");
     if(arr.length>5)
               $(".div li:lt(4)").hide();
   $(".btn").click(function(){
       var arr=$(".div li:not(:hidden)");
       if(arr.length>5)
               $(".div li:lt(4)").hide()
        else
            $(".div li:lt(4)").show()
    });
});
</script>
{% block content %}






				<div class="widget widget-table" >

					<div class="widget-header">
						<i class="icon-th-list"></i>
						<h3>收到简历</h3>
					</div> <!-- /widget-header -->

					<div class="widget-content">

						<table class="table table-striped table-bordered">
							<thead>
								<tr>

									<th>投递人</th>
									<th>岗位名称</th>
                                    <th>薪酬</th>
									<th>是否查看</th>
									<th>&nbsp;</th>
								</tr>
							</thead>

							<tbody>
                            {% for is_offer in page %}
								<tr>

									<td>{{is_offer.user_title}}</td>
									<td>{{is_offer.job}}</td>
                                <td>{{ is_offer.pay }}</td>
									<td>{{is_offer.is_look}}</td>
									<td class="action-td">
										<a href="/show_o/{{ is_offer.user_name }}" class="btn btn-small btn-warning">
											<i class="icon-search"></i>
										</a>


									</td>
								</tr>
                            {% endfor %}
							</tbody>
						</table>

					</div> <!-- /widget-content -->

				</div> <!-- /widget -->

    <nav aria-label="Page navigation" style="position: fixed;right: 60px;bottom: 50px">
        <div class="pagination" >
            <ul class="pagination" >
            {% if page.has_previous %}
                <li><a href="/mana/{{ request.session.cp_title }}/?pindex={{page.previous_page_number}}" aria-label="Previous">
                    <span aria-hidden="true">上一页</span></a></li>
            {% endif %}

            {% for num in page.paginator.page_range%}
                {%if pindex == page.number%}
                    <li ><a href="?pindex=">{{ num }}</a></li>

                {%else%}
                    <li><a href="?pindex={{num}}">{{ num }}</a></li>

                {%endif%}

             {% endfor %}


             {% if page.has_next %}
                 <li><a href="/mana/{{ request.session.cp_title }}/?pindex={{page.next_page_number}}" aria-label="Next">
                      <span aria-hidden="true" >下一页</span></a></li>
              {% endif %}
            </ul>
        </div>
    </nav>
{% endblock %}

templates/cp_register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
     <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="/static/js/jquery-3.4.1.js"></script>
	<script src="/static/bootstrap-4.3.1-dist/js/bootstrap.min.js"></script>
    {% if succ %}
        <script>
        alert({{ succ }})
        </script>
    {% endif %}
</head>
<body>
 <div class="container">
        <div class="col-md-4 col-md-offset-4">
          <form class='form-register' action="/cpregister/" method="post">

              {% if message %}
                  <div class="alert alert-warning">{{ message }}</div>
              {% endif %}

              {% csrf_token %}

              <h2 class="text-center">欢迎注册</h2>
              {{ cpregister_form }}

              <button type="reset" class="btn btn-default pull-left">重置</button>
              <button type="submit" class="btn btn-primary pull-right">提交</button>

          </form>
        </div>
    </div> <!-- /container -->


</body>
</html>

templates/errors.html
{% extends 'index.html' %}
{% block title %}登录{% endblock %}
{% block css %}<link href="/static/css/login.css" rel="stylesheet"/>{% endblock %}
{% block content %}
    <div style="margin-left:100px ">
{% if error_msg %}
    <p>{{ error_msg }}</p>
{% endif %}
    </div>
{% endblock %}

templates/is_apply.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
    <table>
        <tr>
            <th>公司</th>
            <th>岗位</th>
            <th>时间</th>
            <th>是否已被查看</th>
        </tr>
        {% for i in offer %}
        <tr>
        <td>{{ i.cp_title }}</td>
        <td>{{ i.job }}</td>
        <td>{{ i. }}</td>
        <td></td>
        </tr>
        {% endfor %}
    </table>
</div>
{{ offer }}
</body>
</html>

templates/person.html
{% extends 'cp_index.html' %}
{% block title %}详情{% endblock %}
{% block content %}
    <h1 class="page-title">
					<i class="icon-th-list"></i>
					<a  href="#" onClick="javascript :history.back(-1);" style="text-decoration: none;color: whitesmoke">返回</a>
				</h1>
{% for person in user %}
    <h2>{{ person.user_title }}的个人简历</h2><br>
    {{ person.get_user_sex_display }}<br>
    {{ person.user_email }}<br>
    {{ person.address }}<br>
    {{ person.user_tel}}<br>
    {{ person.user_about }}<br>
{% endfor %}
{% endblock %}